### ISSUE TITLE
Exercise Q1: cannot obtain desired mean_predictions

### ISSUE THREAD

**Issue by hugorcf** [LDSSA/batch2-BLU03#1]
On exercise Q1, in the cell starting with `# get in sample predictions`, I obtain `mean_predictions` whose sum is different from the one in the `assert` and the error propagates to all the subsequent exercises.

Without being explicit with the code I used, I followed the standard recipe to create the SARIMAX model - with the required orders and options -, to fit the model and to get the predictions. If I sum the `mean_predictions` I got, I obtain `24865.415873945974`, sufficiently different from the desired result `24838.36`.

Do I need to do something other than the standard recipe at this point, or might there be some other issue?

**Comment by echo66** [comment]
It seems that you are using `enforce_stationarity=False` and `enforce_invertibility=True`. Don't use it, we forgot to take them out of the description. I'm sorry, Hugo.

**Comment by pticao** [comment]
If I take out enforce_stationarity=False then it won't run.... jupyter stays [*]....

**Comment by rafaascensao** [comment]
I have the same problem as @pticao.

**Comment by jtascensao** [comment]
@pticao can you elaborate? On our server, you have successfully completed Q1 by commenting the line `enforce_stationarity=False, enforce_invertibility=True`. Your solution passes the assert.

@rafaascensao you have successfully completed the BLU, your local notebook is still failing?

**Comment by rafaascensao** [comment]
@jtascensao I updated the statsmodels package, and it started working even locally.
