### ISSUE TITLE
Exercise Workflow - 4.1: TypeError: 'numpy.float64' object is not callable

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/batch2-BLU03#2]
There is a poor piece of advice in the instructions, where we advise you in the comments to name your variable `mean_absolute_error`, which will override the name of the function. It then causes trouble later when you are trying to call the function. 

Please name that variable `mae` (or anything else you prefer, just not `mean_absolute_error`. 

Sincere apologies for the mistake. 

![image](https://user-images.githubusercontent.com/8465611/40283235-e9192b82-5c72-11e8-82f0-e8f8f3ae8e77.png)

**Comment by joaobcampos** [comment]
Doesn't the same thing happen later on on question 5?
# fit your Linear Regression 
# r2_score = ...calculate the score of r2

**Comment by PedroGFonseca** [comment]
@joaobcampos it does. That one isn't scored so it does not affect grades, but does indeed.
