### ISSUE TITLE
Learning notebook Part 1 - Sarimax parameters

### ISSUE THREAD

**Issue by antoniopleite** [LDSSA/batch2-BLU03#3]
Although my best_model_params are (1,1,1,0,1,1,14) the example below that optimization fits a model, claiming that it's about to use the best values, with (0,1,1,1,1,1,12) parameters. What am i missing? Some kind of randomness?

**Comment by pma2** [comment]
Any comments about this?

**Comment by deeproute** [comment]
Yea wondering the same thing.
